services:
  - type: web
    name: bookstore-api
    env: docker
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-cvkj9t0dl3ps738k4ulg-a.oregon-postgres.render.com:5432/bookstore_fub5
      - key: SPRING_DATASOURCE_USERNAME
        value: bookstore_fub5_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 7SlmJZkw4BkWspEtq4pAGHX69SJBasH4
      - key: PORT
        value: 10000

databases:
  - name: bookstore_db
    databaseName: bookstore
    plan: free 
